import { ComingBus } from './TransitDetailModel';

export class ComingBusMockData {
  // 所有用户
  static comingBusList: ComingBus[] = [
    {
      stations: 1,
      time: 2,
      distance: 1,
      numberplate: '苏 A0***9F'
    },
    {
      stations: 2,
      time: 4,
      distance: 1,
      numberplate: '苏 A0***0F'
    },
    {
      stations: 3,
      time: 6,
      distance: 1,
      numberplate: '苏 A0***3F'
    },
    {
      stations: 4,
      time: 8,
      distance: 1,
      numberplate: '苏 A0***3F'
    },
    {
      stations: 5,
      time: 10,
      distance: 1,
      numberplate: '苏 A0***3F'
    },
    {
      stations: 6,
      time: 12,
      distance: 1,
      numberplate: '苏 A0***3F'
    },
    {
      stations: 7,
      time: 14,
      distance: 1,
      numberplate: '苏 A0***3F'
    },
    {
      stations: 8,
      time: 16,
      distance: 1,
      numberplate: '苏 A0***3F'
    },
    {
      stations: 9,
      time: 18,
      distance: 1,
      numberplate: '苏 A0***3F'
    },
    {
      stations: 10,
      time: 20,
      distance: 1,
      numberplate: '苏 A0***3F'
    }
  ]
}