import {  BarItem } from '../commons/Types';

export const MOCK_BAR_CHART_LIST: BarItem[] = [
  {
    date: '14:00',
    value: 50,
  },
];

export const MOCK_BAR_CHART_LIST1: BarItem[] = [
  {
    date: '周四',
    value: 50,
  },
  {
    date: '周六',
    value: 20,
  },
];

export const MOCK_BAR_CHART_LIST2: BarItem[] = [
  {
    date: '8-14',
    value: 50,
  },
  {
    date: '8-16',
    value: 20,
  },
  {
    date: '8-29',
    value: 30,
  },
];

export const MOCK_BAR_CHART_LIST3: BarItem[] = [
  {
    date: '2月',
    value: 200,
  },
  {
    date: '3月',
    value: 200,
  },
  {
    date: '6月',
    value: 620,
  },
  {
    date: '7月',
    value: 200,
  },
  {
    date: '11月',
    value: 300,
  },
];

export const MOCK_COLOR_LIST: number[] = [
  0x638750, 0x7ea568, 0x94b982, 0xabd39c, 0xc6e5b9, 0xdff3d7, 0xf2fdee,
];

export const MOCK_COLOR_LIST2: number[] = [
  0xd77525, 0xf2992c, 0xfbb935, 0xffce52, 0xffe38e, 0xfff1ca, 0xfffbef,
];
