/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the 'License');
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an 'AS IS' BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { LeftTab } from './CommonTopic';

export const tabDataList: Array<LeftTab> = [
  {
    id: '1',
    title: '建筑工程',
    list: [
      {
        id: '11',
        title: '建造造价',
        list: [
          {
            id: '111',
            title: '建造师',
            list: [
              {
                id: '1111',
                title: '一级建造师',
                list: [
                  { id: '11111', title: '建筑工程经济' },
                  { id: '11112', title: '建筑工程政治' },
                  { id: '11113', title: '建筑工程教育' },
                  { id: '11114', title: '建筑工程科学' },
                  { id: '11115', title: '建筑工程管理' },
                  { id: '11116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '1112',
                title: '二级建造师',
                list: [
                  { id: '11121', title: '二级建筑工程经济' },
                  { id: '11122', title: '二级建筑工程政治' },
                  { id: '11123', title: '二级建筑工程教育' },
                  { id: '11124', title: '二级建筑工程科学' },
                  { id: '11125', title: '二级建筑工程管理' },
                  { id: '11126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '2',
    title: '考公考编',
    list: [
      {
        id: '21',
        title: '考公',
        list: [
          {
            id: '211',
            title: '公务员',
            list: [
              {
                id: '2111',
                title: '一级公务员',
                list: [
                  { id: '21111', title: '建筑工程经济' },
                  { id: '21112', title: '建筑工程政治' },
                  { id: '21113', title: '建筑工程教育' },
                  { id: '21114', title: '建筑工程科学' },
                  { id: '21115', title: '建筑工程管理' },
                  { id: '21116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '2112',
                title: '二级公务员',
                list: [
                  { id: '21121', title: '二级建筑工程经济' },
                  { id: '21122', title: '二级建筑工程政治' },
                  { id: '21123', title: '二级建筑工程教育' },
                  { id: '21124', title: '二级建筑工程科学' },
                  { id: '21125', title: '二级建筑工程管理' },
                  { id: '21126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '3',
    title: '生产运输管理职业资格技术类型分类',
    list: [
      {
        id: '31',
        title: '事业单位',
        list: [
          {
            id: '311',
            title: '在编',
            list: [
              {
                id: '3111',
                title: '一级在编',
                list: [
                  { id: '31111', title: '建筑工程经济' },
                  { id: '31112', title: '建筑工程政治' },
                  { id: '31113', title: '建筑工程教育' },
                  { id: '31114', title: '建筑工程科学' },
                  { id: '31115', title: '建筑工程管理' },
                  { id: '31116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '3112',
                title: '二级在编',
                list: [
                  { id: '31121', title: '二级建筑工程经济' },
                  { id: '31122', title: '二级建筑工程政治' },
                  { id: '31123', title: '二级建筑工程教育' },
                  { id: '31124', title: '二级建筑工程科学' },
                  { id: '31125', title: '二级建筑工程管理' },
                  { id: '31126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '4',
    title: '职业资格',
    list: [
      {
        id: '41',
        title: '事业单位',
        list: [
          {
            id: '411',
            title: '在编',
            list: [
              {
                id: '4111',
                title: '一级在编',
                list: [
                  { id: '41111', title: '建筑工程经济' },
                  { id: '41112', title: '建筑工程政治' },
                  { id: '41113', title: '建筑工程教育' },
                  { id: '41114', title: '建筑工程科学' },
                  { id: '41115', title: '建筑工程管理' },
                  { id: '41116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '4112',
                title: '二级在编',
                list: [
                  { id: '41121', title: '二级建筑工程经济' },
                  { id: '41122', title: '二级建筑工程政治' },
                  { id: '41123', title: '二级建筑工程教育' },
                  { id: '41124', title: '二级建筑工程科学' },
                  { id: '41125', title: '二级建筑工程管理' },
                  { id: '41126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '5',
    title: '职业资格',
    list: [
      {
        id: '51',
        title: '事业单位',
        list: [
          {
            id: '511',
            title: '在编',
            list: [
              {
                id: '5111',
                title: '一级在编',
                list: [
                  { id: '51111', title: '建筑工程经济' },
                  { id: '51112', title: '建筑工程政治' },
                  { id: '51113', title: '建筑工程教育' },
                  { id: '51114', title: '建筑工程科学' },
                  { id: '51115', title: '建筑工程管理' },
                  { id: '51116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '5112',
                title: '二级在编',
                list: [
                  { id: '51121', title: '二级建筑工程经济' },
                  { id: '51122', title: '二级建筑工程政治' },
                  { id: '51123', title: '二级建筑工程教育' },
                  { id: '51124', title: '二级建筑工程科学' },
                  { id: '51125', title: '二级建筑工程管理' },
                  { id: '51126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '6',
    title: '职业资格',
    list: [
      {
        id: '61',
        title: '事业单位',
        list: [
          {
            id: '611',
            title: '在编',
            list: [
              {
                id: '6111',
                title: '一级在编',
                list: [
                  { id: '61111', title: '建筑工程经济' },
                  { id: '61112', title: '建筑工程政治' },
                  { id: '61113', title: '建筑工程教育' },
                  { id: '61114', title: '建筑工程科学' },
                  { id: '61115', title: '建筑工程管理' },
                  { id: '61116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '6112',
                title: '二级在编',
                list: [
                  { id: '61121', title: '二级建筑工程经济' },
                  { id: '61122', title: '二级建筑工程政治' },
                  { id: '61123', title: '二级建筑工程教育' },
                  { id: '61124', title: '二级建筑工程科学' },
                  { id: '61125', title: '二级建筑工程管理' },
                  { id: '61126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '7',
    title: '职业资格',
    list: [
      {
        id: '71',
        title: '事业单位',
        list: [
          {
            id: '711',
            title: '在编',
            list: [
              {
                id: '7111',
                title: '一级在编',
                list: [
                  { id: '71111', title: '建筑工程经济' },
                  { id: '71112', title: '建筑工程政治' },
                  { id: '71113', title: '建筑工程教育' },
                  { id: '71114', title: '建筑工程科学' },
                  { id: '71115', title: '建筑工程管理' },
                  { id: '71116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '7112',
                title: '二级在编',
                list: [
                  { id: '71121', title: '二级建筑工程经济' },
                  { id: '71122', title: '二级建筑工程政治' },
                  { id: '71123', title: '二级建筑工程教育' },
                  { id: '71124', title: '二级建筑工程科学' },
                  { id: '71125', title: '二级建筑工程管理' },
                  { id: '71126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '8',
    title: '职业资格',
    list: [
      {
        id: '81',
        title: '事业单位',
        list: [
          {
            id: '811',
            title: '在编',
            list: [
              {
                id: '8111',
                title: '一级在编',
                list: [
                  { id: '81111', title: '建筑工程经济' },
                  { id: '81112', title: '建筑工程政治' },
                  { id: '81113', title: '建筑工程教育' },
                  { id: '81114', title: '建筑工程科学' },
                  { id: '81115', title: '建筑工程管理' },
                  { id: '81116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '8112',
                title: '二级在编',
                list: [
                  { id: '81121', title: '二级建筑工程经济' },
                  { id: '81122', title: '二级建筑工程政治' },
                  { id: '81123', title: '二级建筑工程教育' },
                  { id: '81124', title: '二级建筑工程科学' },
                  { id: '81125', title: '二级建筑工程管理' },
                  { id: '81126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '9',
    title: '职业资格',
    list: [
      {
        id: '91',
        title: '事业单位',
        list: [
          {
            id: '911',
            title: '在编',
            list: [
              {
                id: '9111',
                title: '一级在编',
                list: [
                  { id: '91111', title: '建筑工程经济' },
                  { id: '91112', title: '建筑工程政治' },
                  { id: '91113', title: '建筑工程教育' },
                  { id: '91114', title: '建筑工程科学' },
                  { id: '91115', title: '建筑工程管理' },
                  { id: '91116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '9112',
                title: '二级在编',
                list: [
                  { id: '91121', title: '二级建筑工程经济' },
                  { id: '91122', title: '二级建筑工程政治' },
                  { id: '91123', title: '二级建筑工程教育' },
                  { id: '91124', title: '二级建筑工程科学' },
                  { id: '91125', title: '二级建筑工程管理' },
                  { id: '91126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '10',
    title: '职业资格',
    list: [
      {
        id: '101',
        title: '事业单位',
        list: [
          {
            id: '1011',
            title: '在编',
            list: [
              {
                id: '10111',
                title: '一级在编',
                list: [
                  { id: '101111', title: '建筑工程经济' },
                  { id: '101112', title: '建筑工程政治' },
                  { id: '101113', title: '建筑工程教育' },
                  { id: '101114', title: '建筑工程科学' },
                  { id: '101115', title: '建筑工程管理' },
                  { id: '101116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '10112',
                title: '二级在编',
                list: [
                  { id: '101121', title: '二级建筑工程经济' },
                  { id: '101122', title: '二级建筑工程政治' },
                  { id: '101123', title: '二级建筑工程教育' },
                  { id: '101124', title: '二级建筑工程科学' },
                  { id: '101125', title: '二级建筑工程管理' },
                  { id: '101126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '11',
    title: '职业资格',
    list: [
      {
        id: '111',
        title: '事业单位',
        list: [
          {
            id: '1111',
            title: '在编',
            list: [
              {
                id: '11111',
                title: '一级在编',
                list: [
                  { id: '111111', title: '建筑工程经济' },
                  { id: '111112', title: '建筑工程政治' },
                  { id: '111113', title: '建筑工程教育' },
                  { id: '111114', title: '建筑工程科学' },
                  { id: '111115', title: '建筑工程管理' },
                  { id: '111116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '11112',
                title: '二级在编',
                list: [
                  { id: '111121', title: '二级建筑工程经济' },
                  { id: '111122', title: '二级建筑工程政治' },
                  { id: '111123', title: '二级建筑工程教育' },
                  { id: '111124', title: '二级建筑工程科学' },
                  { id: '111125', title: '二级建筑工程管理' },
                  { id: '111126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '12',
    title: '职业资格',
    list: [
      {
        id: '121',
        title: '事业单位',
        list: [
          {
            id: '1211',
            title: '在编',
            list: [
              {
                id: '12111',
                title: '一级在编',
                list: [
                  { id: '121111', title: '建筑工程经济' },
                  { id: '121112', title: '建筑工程政治' },
                  { id: '121113', title: '建筑工程教育' },
                  { id: '121114', title: '建筑工程科学' },
                  { id: '121115', title: '建筑工程管理' },
                  { id: '121116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '12112',
                title: '二级在编',
                list: [
                  { id: '121121', title: '二级建筑工程经济' },
                  { id: '121122', title: '二级建筑工程政治' },
                  { id: '121123', title: '二级建筑工程教育' },
                  { id: '121124', title: '二级建筑工程科学' },
                  { id: '121125', title: '二级建筑工程管理' },
                  { id: '121126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '13',
    title: '职业资格',
    list: [
      {
        id: '131',
        title: '事业单位',
        list: [
          {
            id: '1311',
            title: '在编',
            list: [
              {
                id: '13111',
                title: '一级在编',
                list: [
                  { id: '131111', title: '建筑工程经济' },
                  { id: '131112', title: '建筑工程政治' },
                  { id: '131113', title: '建筑工程教育' },
                  { id: '131114', title: '建筑工程科学' },
                  { id: '131115', title: '建筑工程管理' },
                  { id: '131116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '13112',
                title: '二级在编',
                list: [
                  { id: '131121', title: '二级建筑工程经济' },
                  { id: '131122', title: '二级建筑工程政治' },
                  { id: '131123', title: '二级建筑工程教育' },
                  { id: '131124', title: '二级建筑工程科学' },
                  { id: '131125', title: '二级建筑工程管理' },
                  { id: '131126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '14',
    title: '职业资格',
    list: [
      {
        id: '141',
        title: '事业单位',
        list: [
          {
            id: '1411',
            title: '在编',
            list: [
              {
                id: '14111',
                title: '一级在编',
                list: [
                  { id: '141111', title: '建筑工程经济' },
                  { id: '141112', title: '建筑工程政治' },
                  { id: '141113', title: '建筑工程教育' },
                  { id: '141114', title: '建筑工程科学' },
                  { id: '141115', title: '建筑工程管理' },
                  { id: '141116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '14112',
                title: '二级在编',
                list: [
                  { id: '141121', title: '二级建筑工程经济' },
                  { id: '141122', title: '二级建筑工程政治' },
                  { id: '141123', title: '二级建筑工程教育' },
                  { id: '141124', title: '二级建筑工程科学' },
                  { id: '141125', title: '二级建筑工程管理' },
                  { id: '141126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '15',
    title: '职业资格',
    list: [
      {
        id: '151',
        title: '事业单位',
        list: [
          {
            id: '1511',
            title: '在编',
            list: [
              {
                id: '15111',
                title: '一级在编',
                list: [
                  { id: '151111', title: '建筑工程经济' },
                  { id: '151112', title: '建筑工程政治' },
                  { id: '151113', title: '建筑工程教育' },
                  { id: '151114', title: '建筑工程科学' },
                  { id: '151115', title: '建筑工程管理' },
                  { id: '151116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '15112',
                title: '二级在编',
                list: [
                  { id: '151121', title: '二级建筑工程经济' },
                  { id: '151122', title: '二级建筑工程政治' },
                  { id: '151123', title: '二级建筑工程教育' },
                  { id: '151124', title: '二级建筑工程科学' },
                  { id: '151125', title: '二级建筑工程管理' },
                  { id: '151126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '16',
    title: '职业资格',
    list: [
      {
        id: '161',
        title: '事业单位',
        list: [
          {
            id: '1611',
            title: '在编',
            list: [
              {
                id: '16111',
                title: '一级在编',
                list: [
                  { id: '161111', title: '建筑工程经济' },
                  { id: '161112', title: '建筑工程政治' },
                  { id: '161113', title: '建筑工程教育' },
                  { id: '161114', title: '建筑工程科学' },
                  { id: '161115', title: '建筑工程管理' },
                  { id: '161116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '16112',
                title: '二级在编',
                list: [
                  { id: '161121', title: '二级建筑工程经济' },
                  { id: '161122', title: '二级建筑工程政治' },
                  { id: '161123', title: '二级建筑工程教育' },
                  { id: '161124', title: '二级建筑工程科学' },
                  { id: '161125', title: '二级建筑工程管理' },
                  { id: '161126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '17',
    title: '职业资格',
    list: [
      {
        id: '171',
        title: '事业单位',
        list: [
          {
            id: '1711',
            title: '在编',
            list: [
              {
                id: '17111',
                title: '一级在编',
                list: [
                  { id: '171111', title: '建筑工程经济' },
                  { id: '171112', title: '建筑工程政治' },
                  { id: '171113', title: '建筑工程教育' },
                  { id: '171114', title: '建筑工程科学' },
                  { id: '171115', title: '建筑工程管理' },
                  { id: '171116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '17112',
                title: '二级在编',
                list: [
                  { id: '171121', title: '二级建筑工程经济' },
                  { id: '171122', title: '二级建筑工程政治' },
                  { id: '171123', title: '二级建筑工程教育' },
                  { id: '171124', title: '二级建筑工程科学' },
                  { id: '171125', title: '二级建筑工程管理' },
                  { id: '171126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '18',
    title: '职业资格',
    list: [
      {
        id: '181',
        title: '事业单位',
        list: [
          {
            id: '1811',
            title: '在编',
            list: [
              {
                id: '18111',
                title: '一级在编',
                list: [
                  { id: '181111', title: '建筑工程经济' },
                  { id: '181112', title: '建筑工程政治' },
                  { id: '181113', title: '建筑工程教育' },
                  { id: '181114', title: '建筑工程科学' },
                  { id: '181115', title: '建筑工程管理' },
                  { id: '181116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '18112',
                title: '二级在编',
                list: [
                  { id: '181121', title: '二级建筑工程经济' },
                  { id: '181122', title: '二级建筑工程政治' },
                  { id: '181123', title: '二级建筑工程教育' },
                  { id: '181124', title: '二级建筑工程科学' },
                  { id: '181125', title: '二级建筑工程管理' },
                  { id: '181126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '19',
    title: '职业资格',
    list: [
      {
        id: '191',
        title: '事业单位',
        list: [
          {
            id: '1911',
            title: '在编',
            list: [
              {
                id: '19111',
                title: '一级在编',
                list: [
                  { id: '191111', title: '建筑工程经济' },
                  { id: '191112', title: '建筑工程政治' },
                  { id: '191113', title: '建筑工程教育' },
                  { id: '191114', title: '建筑工程科学' },
                  { id: '191115', title: '建筑工程管理' },
                  { id: '191116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '19112',
                title: '二级在编',
                list: [
                  { id: '191121', title: '二级建筑工程经济' },
                  { id: '191122', title: '二级建筑工程政治' },
                  { id: '191123', title: '二级建筑工程教育' },
                  { id: '191124', title: '二级建筑工程科学' },
                  { id: '191125', title: '二级建筑工程管理' },
                  { id: '191126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
  {
    id: '20',
    title: '职业资格',
    list: [
      {
        id: '201',
        title: '事业单位',
        list: [
          {
            id: '2011',
            title: '在编',
            list: [
              {
                id: '20111',
                title: '一级在编',
                list: [
                  { id: '201111', title: '建筑工程经济' },
                  { id: '201112', title: '建筑工程政治' },
                  { id: '201113', title: '建筑工程教育' },
                  { id: '201114', title: '建筑工程科学' },
                  { id: '201115', title: '建筑工程管理' },
                  { id: '201116', title: '建筑工程统筹' }
                ]
              },
              {
                id: '20112',
                title: '二级在编',
                list: [
                  { id: '201121', title: '二级建筑工程经济' },
                  { id: '201122', title: '二级建筑工程政治' },
                  { id: '201123', title: '二级建筑工程教育' },
                  { id: '201124', title: '二级建筑工程科学' },
                  { id: '201125', title: '二级建筑工程管理' },
                  { id: '201126', title: '二级建筑工程统筹' },
                ]
              },
            ]
          }
        ]
      },
    ],
  },
]



