import { HistorySearchItem, HotSearchItem } from '../../commons/Types';

export const HISTORY_SEARCH_MOCK: HistorySearchItem[] = [
  {
    label: 'X-面板',
    latestSearch: 1751887063146,
  },
  {
    label: '动物壁纸',
    latestSearch: 1751887063100,
  },
  {
    label: '天气壁纸',
    latestSearch: 175188706000,
  },
  {
    label: '充电特效',
    latestSearch: 175188706001,
  },
];

export const GUESS_LIKE_LIST1: string[] = [
  '天气',
  '纪念日',
  '时钟组件',
  '步数组件',
];

export const GUESS_LIKE_LIST2: string[] = [
  '敲木鱼',
  '表情电量',
  '糖果袋吧唧',
  '吧唧',
];

export const HOT_SEARCH_MOCK: HotSearchItem[] = [
  {
    label: 'Q萌ID卡',
    hotRate: 722.2,
  },
  {
    label: '相册',
    hotRate: 642.6,
  },
  {
    label: '照片',
    hotRate: 495.2,
  },
  {
    label: '表情电量',
    hotRate: 78.5,
  },
  {
    label: '答案之书',
    hotRate: 76.2,
  },
  {
    label: '动漫壁纸',
    hotRate: 72.7,
  },
  {
    label: '风景',
    hotRate: 69.9,
  },
  {
    label: '科幻壁纸',
    hotRate: 68.2,
  },
  {
    label: '游戏壁纸',
    hotRate: 60.1,
  },
  {
    label: '小清新',
    hotRate: 55.5,
  },
];