export enum RouterMap {
  // phone模块
  INDEX_PAGE = 'IndexPage',
  SAFE_PAGE = 'SafePage',
  SPLASH_PAGE = 'SplashPage',
  PRIVACY_PAGE = 'PrivacyPage',
  AGREE_PRIVACY_PAGE = 'AgreePrivacyPage',
  START_PAGE = 'StartPage',
  // 首页模块
  SEARCH_PAGE = 'SearchPage',
  NEW_UPLOAD_PAGE = 'NewUpLoadPage',
  NEW_UPLOAD_RECORD = 'NewUploadRecord',
  LATEST = 'LatestPage',
  POPULAR = 'Popular',
  FREEPAGE = 'FreePage',
  // 账号模块
  HUAWEI_LOGIN_PAGE = 'HuaweiLoginPage',
  OTHER_LOGIN_PAGE = 'OtherLoginPage',
  PROTOCOL_WEBVIEW = 'ProtocolWebView',
  // 我的模块
  NEW_MINE_MARK_PAGE = 'NewMarkPage',
  MINE_LIKE_PAGE = 'UploadRecord',
  VIPCENTER_PAGE = 'VipCenterPage',
  // 设置模块
  SETTING_PAGE = 'SettingPage',
  SETTING_ABOUT = 'SettingAbout',
  // 个人主页模块
  PERSONAL = 'Personal',
  // 意见反馈模块
  FEEDBACK_PAGE = 'FeedbackPage',
  // 桌面小组件模块
  TUTORIAL_PAGE = 'TutorialPage',
  MY_COMPONENT_PAGE = 'MyComponentPage',
  LOGIN_PAGE = 'LOGIN_PAGE',
  NEW_ROUTER_MAP_WALLPAPER_DETAIL = 'NewWallpaperDetailPage',
  COMPONENT_DETAIL_PAGE = 'ComponentDetailPage',
}