export enum BusSubwayMap {
  /**
   * 公交类型
   */
  BUS_SUBWAY_TYPE_BUS = '0',

  /**
   * 地铁类型
   */
  BUS_SUBWAY_TYPE_SUBWAY = '1',

}

export enum BusCrowdStateMap {
  /**
   * 轻松舒适
   */
  COMFORTABLE = '0',

  /**
   * 轻微拥堵
   */
  SLIGHT_CROWD = '1',

  /**
   * 严重拥堵
   */
  SEVERE_CROWD = '2',

}

export enum LineCongestionStateMap {
  /**
   * 轻松舒适
   */
  COMFORTABLE = '0',

  /**
   * 轻微拥堵
   */
  SLIGHT_CROWD = '1',

  /**
   * 严重拥堵
   */
  SEVERE_CROWD = '2',

}

export enum SubWayCarCrowdStateMap {
  /**
   * 轻松舒适
   */
  COMFORTABLE = '0',

  /**
   * 轻微拥堵
   */
  SLIGHT_CROWD = '1',

  /**
   * 严重拥堵
   */
  SEVERE_CROWD = '2',

}

export enum SubWayCarTempretureStateMap {
  /**
   * 弱冷车厢
   */
  WEAK_COLD = '0',

  /**
   * 强冷车厢
   */
  STRONG_COLD = '1',

  /**
   * 商务车厢
   */
  BUSINESS = '2',

}

