/**
 * Common constants for common component.
 */
export class LineCommonConstants {
  // Space
  static readonly SPACE_XXS: number = 2;
  static readonly SPACE_XS: number = 4;
  static readonly SPACE_S: number = 8;
  static readonly SPACE_M: number = 12;
  static readonly SPACE_L: number = 16;
  static readonly SPACE_XL: number = 20;
  static readonly SPACE_XXL: number = 24;
  // Percent
  static readonly FULL_PERCENT: string = '100%';
  static readonly HALF_PERCENT: string = '50%';
  // Padding
  static readonly PADDING_XXS: number = 2;
  static readonly PADDING_XS: number = 4;
  static readonly PADDING_S: number = 8;
  static readonly PADDING_M: number = 12;
  static readonly PADDING_L: number = 16;
  static readonly PADDING_XL: number = 20;
  static readonly PADDING_XXL: number = 24;
  static readonly PADDING_PAGE: number = 16;
  // Setting
  static readonly SETTING_SPEED: number[] = [10, 30, 60]
  // 站点一半的距离 单位公里
  static readonly HALF_DISTANCE_BETWEEN_STOP: number = 1
  // 站点一半的距离 单位公里
  static readonly HALF_TIME_BETWEEN_STOP: number = 1
}
