import { ProductCardItem } from '../commons/Types';

export const MOCK_PRODUCT_LIST1: ProductCardItem[] = [
  {
    productId: 'product_20001',
    price: 98,
    dashPrice: 128,
    title: '休闲简约经典商务衬衫T恤日系风高级感',
    banner: $r('app.media.mock2_spec_black'),
    promotion: ['单件包邮'],
    label: [
      {
        preset: 1,
        data: '热销爆款',
      },
    ],
  },
  {
    productId: 'product_20002',
    price: 98,
    dashPrice: 128,
    title: '休闲简约经典商务衬衫T恤日系风高级感',
    banner: $r('app.media.mock2_spec_blue'),
    promotion: ['单件包邮'],
    label: [
      {
        preset: 1,
        data: '热销爆款',
      },
    ],
  },
  {
    productId: 'product_20003',
    price: 98,
    dashPrice: 128,
    title: '休闲简约经典商务衬衫T恤日系风高级感',
    banner: $r('app.media.mock2_spec_shirt'),
    promotion: [],
    label: [],
  },
  {
    productId: 'product_20004',
    price: 98,
    dashPrice: 128,
    title: '休闲简约经典商务衬衫T恤日系风高级感',
    banner: $r('app.media.mock2_spec_white'),
    promotion: [],
    label: [],
  },
  {
    productId: 'product_20001',
    price: 98,
    dashPrice: 128,
    title: '休闲简约经典商务衬衫T恤日系风高级感',
    banner: $r('app.media.mock2_spec_black'),
    promotion: ['单件包邮'],
    label: [
      {
        preset: 1,
        data: '热销爆款',
      },
    ],
  },
  {
    productId: 'product_20002',
    price: 98,
    dashPrice: 128,
    title: '休闲简约经典商务衬衫T恤日系风高级感',
    banner: $r('app.media.mock2_spec_blue'),
    promotion: ['单件包邮'],
    label: [
      {
        preset: 1,
        data: '热销爆款',
      },
    ],
  },
  {
    productId: 'product_20003',
    price: 98,
    dashPrice: 128,
    title: '休闲简约经典商务衬衫T恤日系风高级感',
    banner: $r('app.media.mock2_spec_shirt'),
    promotion: [],
    label: [],
  },
  {
    productId: 'product_20004',
    price: 98,
    dashPrice: 128,
    title: '休闲简约经典商务衬衫T恤日系风高级感',
    banner: $r('app.media.mock2_spec_white'),
    promotion: [],
    label: [],
  },
]

export const MOCK_PRODUCT_LIST2: ProductCardItem[] = [
  {
    productId: 'product_10001',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_pink'),
    promotion: ['任选2件7.5折,任选3件7折'],
    label: [
      {
        preset: 0,
        data: '上新折扣',
      },
      {
        preset: 1,
        data: '热销爆款',
      },
    ],
  },
  {
    productId: 'product_10002',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_white'),
    promotion: [],
    label: [],
  },
  {
    productId: 'product_10003',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_stripe'),
    promotion: ['8.5折'],
    label: [],
  },
  {
    productId: 'product_10004',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_green'),
    promotion: [],
    label: [],
  },
  {
    productId: 'product_10001',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_pink'),
    promotion: ['任选2件7.5折,任选3件7折'],
    label: [
      {
        preset: 0,
        data: '上新折扣',
      },
      {
        preset: 1,
        data: '热销爆款',
      },
    ],
  },
  {
    productId: 'product_10002',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_white'),
    promotion: [],
    label: [],
  },
  {
    productId: 'product_10003',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_stripe'),
    promotion: ['8.5折'],
    label: [],
  },
  {
    productId: 'product_10004',
    price: 188,
    dashPrice: 200,
    title: '时尚轻商务系列针织打底纯羊毛内搭',
    banner: $r('app.media.mock_spec_green'),
    promotion: [],
    label: [],
  },
];

