/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export { HomePageBuilder } from './src/main/ets/pages/MainPage';

export { FeaturedCoursesBuilder } from './src/main/ets/pages/FeaturedCourses';

export { MaterialDownloadBuilder } from './src/main/ets/pages/MaterialDownload';

export { ChapterPracticeBuilder } from './src/main/ets/pages/ChapterPractice';

export { SearchPageBuilder } from './src/main/ets/pages/SearchIndexPage'

export { SearchInputBuilder } from './src/main/ets/pages/SearchInputPage'

export { SecondListBuilder } from './src/main/ets/pages/SecondListPage';

export { ThirdListBuilder } from './src/main/ets/pages/ThirdListPage';

export { TopicHomePageBuilder } from './src/main/ets/pages/TopicHomePage';