export class Constants {
  public static readonly BTN_HEIGHT: number = 40;
  public static readonly PADDING_40: number = 40;
  public static readonly START_ICON_WIDTH: number = 72;
  public static readonly WAY_ICON_WIDTH: number = 48;
  public static readonly WAY_WIDTH: number = 100;
  public static readonly INPUT_HEIGHT: number = 56;
  public static readonly DEFAULT_LOGIN_SHEET_HEIGHT: number = 620
  public static readonly LOGIN_SHEET_STACK_NAME: string = 'loginSheetStackName';
}