
export class RouterConst {

  public static readonly MAIN_ABILITY_NAME: string = 'EntryAbility';

  public static readonly MAIN_ENTRY_PAGE_PATH: string = 'pages/MainEntry';

  public static readonly TIMETABLE_PAGE_NAME: string = 'TimetablePage';

  public static readonly COURSE_FORM_PAGE_NAME: string = 'CourseFormPage';

  public static readonly COURSE_DETAIL_PAGE_NAME: string = 'CourseDetailPage';
}
