export enum PageName {
  JobIntentions = 'JobIntentionsPage',
  CareerObjective = 'CareerObjectivePage',
  CategorySelect = 'CategorySelectPage',
  IndustrySelect = 'IndustrySelectPage',
  CitySelect = 'CitySelect'
}

export enum BreakpointType {
  XS = 'xs',
  SM = 'sm',
  MD = 'md',
  LG = 'lg',
  XL = 'xl',
  XXL = 'xxl'
}

export enum StandardCharsets {
  GBK = 'gbk',
  ISO_8859_1 = 'iso-8859-1',
  US_ASCII = 'us-ascii',
  UTF_8 = 'utf-8',
  UTF_16 = 'utf-16'
}
