export enum RouterMap {
  // phone模块
  INDEX_PAGE = 'IndexPage',
  SAFE_PAGE = 'SafePage',
  SPLASH_PAGE = 'SplashPage',
  PRIVACY_PAGE = 'PrivacyPage',
  AGREE_PRIVACY_PAGE = 'AgreePrivacyPage',

  // 首页模块
  HOME_PAGE = 'HomePage',
  NEWS_SEARCH = 'NewsSearch',
  NEWS_POST = 'NewsPost',
  NEWS_PUBLISH_SELECT = 'NewsPublishSelect',
  // 图片预览
  IMAGE_PREVIEW = 'ImagePreview',
  // 视频预览
  Video_PREVIEW = 'VideoPreview',
  // 视频模块
  VIDEO_PAGE = 'VideoPage',
  VIDEO_DETAIL_PAGE = 'VideoDetailPage',
  VIDEO_LANDSCAPE_PAGE = 'LandscapeVideo',
  LIVESTREAM_DETAIL_PAGE = 'LivestreamDetailPage',
  // 账号模块
  HUAWEI_LOGIN_PAGE = 'HuaweiLoginPage',
  OTHER_LOGIN_PAGE = 'OtherLoginPage',
  PROTOCOL_WEBVIEW = 'ProtocolWebView',
  // 文章详情
  ARTICLE_FEED_DETAILS = 'ArticleFeedDetails',
  // 互动模块
  PUBLISH_POST_PAGE = 'PublishPostPage',
  // 我的模块
  MINE_COMMENT_PAGE = 'CommentPage',
  MINE_MESSAGE_PAGE = 'MessagePage',
  MINE_MARK_PAGE = 'MarkPage',
  MINE_LIKE_PAGE = 'LikePage',
  MINE_HISTORY_PAGE = 'HistoryPage',
  MINE_MSG_COMMENT = 'MessageCommentReplyPage',
  MINE_MSG_COMMENT_DETAIL = 'MessageSingleCommentList',
  MINE_MSG_FANS = 'MessageFansPage',
  MINE_MSG_IM = 'MessageIMPage',
  MINE_MSG_SYSTEM = 'MessageSystemPage',
  MINE_MSG_IM_CHAT = 'MessageIMChatPage',
  // 设置模块
  SETTING_PAGE = 'SettingPage',
  SETTING_PERSONAL = 'SettingPersonal',
  SETTING_PRIVACY = 'SettingPrivacy',
  SETTING_NETWORK = 'SettingNetwork',
  SETTING_FONT = 'SettingFont',
  SETTING_ABOUT = 'SettingAbout',
  SETTING_H5 = 'SettingH5',
  // 个人主页模块
  PROFILE_HOME = 'PersonalHomePage',
  PROFILE_WATCH = 'WatchPage',
  PROFILE_FOLLOWER = 'FollowerPage',
  // 意见反馈模块
  FEEDBACK_PAGE = 'FeedbackPage',
}