/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export { HomePageBuilder } from './src/main/ets/pages/HomePage';

export { RecordedDetailBuilder } from './src/main/ets/pages/RecordedDetail';

export { ChapterDetailBuilder } from './src/main/ets/pages/ChapterDetail';

export { SearchPageBuilder } from './src/main/ets/pages/HomeSearch';

export { CourseListPageBuilder } from './src/main/ets/pages/CourseListPage';

export { LiveStreamingListPageBuilder } from './src/main/ets/pages/LiveStreamingListPage';

export { MaterialPageBuilder } from './src/main/ets/pages/MaterialPage';

export { TestReportBuilder } from './src/main/ets/pages/TestReportPage';

export { AnswerQuestionsBuilder } from './src/main/ets/pages/AnswerQuestionsPage';

export { AnswerQuestionsExamBuilder } from './src/main/ets/pages/AnswerQuestionsExamPage';

export { ExamResultBuilder } from './src/main/ets/pages/ExamResultPage';

export { LookFileBuilder } from './src/main/ets/pages/LookFilePage';

export { LiveDetailPageBuilder } from './src/main/ets/pages/LiveDetailPage';

export { LiveStreamingPageBuilder } from './src/main/ets/pages/LiveStreamingPage';

export { InputCommentBuilder } from './src/main/ets/pages/InputCommentPage';
