/**
 * 页面路由注册
 */
export class RouterMap {
  // app隐私
  public static readonly PRIVACY_AGREEMENT_PAGE = 'PrivacyAgreementPage'
  // 协议内容页
  public static readonly PROTOCOL_WEB_VIEW_NAME = 'ProtocolWebView'
  // 首页
  public static readonly MAIN_PAGE = 'MainPage'
  // 登录页面
  public static readonly LOGIN_PAGE = 'LoginPage'
  // 意见反馈
  public static readonly FEEDBACK_PAGE = 'FeedbackPage'
  // 个人信息页
  public static readonly PERSONAL_CENTER_PAGE = 'EditPersonalCenter'
  // 简历-个人信息编辑页
  public static readonly RESUME_PERSONAL_INFO_PAGE = 'ResumePersonalInformationPage'
  // 简历-教育背景编辑页
  public static readonly RESUME_EDUCATION_BACKGROUND_PAGE = 'ResumeEducationBackgroundPage'
  // 简历-工作经历编辑页
  public static readonly RESUME_WORK_EXPERIENCE_PAGE = 'ResumeWorkExperiencePage'
  // 隐私设置
  public static readonly PRIVACY_SETTINGS_PAGE = 'PrivacySettingsPage'
  // 关于
  public static readonly ABOUT_PAGE = 'AboutPage'
  // 三方信息共享清单
  public static readonly PRIVACY_3RD_PARTY_SHARE_PAGE = 'Privacy3rdPartySharePage'
  // 个人信息收集清单
  public static readonly PRIVACY_INFO_COLLECT_PAGE = 'PrivacyInfoCollectPage'
  // 设置页面
  public static readonly SET_UP_PAGE = 'SetUpPage'
  // 搜索框
  public static readonly SEARCH_PAGE = 'SearchPage'
  // 简历页面
  public static readonly RESUME_PAGE = 'ResumePage'
  // 模板详情
  public static readonly TEMPLATE_DETAIL_PAGE = 'TemplateDetailPage'
  public static readonly MY_RESUME_PAGE = 'MyResumePage'
  public static readonly MY_FAVORITES_PAGE = 'FavoritesPage'
  // 简历-模板-使用此模板-预览页
  public static readonly TEMPLATE_RESUME_PREVIEW_PAGE = 'ResumePreviewPage'
  // 简历-职位选择
  public static readonly RESUME_POSITION_SELECT_PAGE = 'PositionSelectPage'
  // 简历-行业选择
  public static readonly RESUME_INDUSTRY_SELECT_PAGE = 'IndustrySelectPage'
  // 简历-工作描述编辑
  public static readonly RESUME_WORK_DESCRIPTION_PAGE = 'WorkDescriptionPage'
  // 简历-项目经验编辑页
  public static readonly RESUME_PROJECT_EXPERIENCE_PAGE = 'ResumeProjectExperiencePage'
  // 简历-项目经验-角色选择
  public static readonly RESUME_ROLE_SELECT_PAGE = 'RoleSelectPage'
  // 简历-项目经验-项目描述编辑
  public static readonly RESUME_PROJECT_DESCRIPTION_PAGE = 'ProjectDescriptionPage'
  // 简历-职业技能编辑
  public static readonly RESUME_VOCATIONAL_SKILL_PAGE = 'VocationalSkillPage'
  // 简历-自我评价编辑
  public static readonly RESUME_SELF_EVALUATION_PAGE = 'SelfEvaluationPage'
  // 简历-求职意向编辑
  public static readonly RESUME_CAREER_OBJECTIVE_PAGE = 'CareerObjectivePage'
  // 简历-城市选择
  public static readonly RESUME_CITY_SELECT_PAGE = 'CitySelectPage'
  // 简历-资格证书选择
  public static readonly RESUME_QUALIFICATION_CERTIFICATE_PAGE = 'QualificationCertificatePage'
}

