export enum RouterMap {
  // 首开申请用户许可
  SAFE_PAGE = 'SafePage',
  // 主入口
  MAIN_ENTRY = 'MainEntry',

  SETTING = 'SettingPage',
  AGREEMENT = 'AgreementPage',
  USER_LOGIN = 'HuaweiQuickLoginPage',
  USER_OTHER_LOGIN = 'OtherLoginPage',
  USER_PROFILE_EDIT = 'EditProfilePage',
  USER_COUPON_PAGE = 'CouponPage',

  PRODUCT_SEARCH = 'ProductSearchPage',
  PRODUCT_SEARCH_RESULTS = 'ProductSearchResultsPage',
  PRODUCT_INFO = 'ProductInfoPage',
  PRODUCT_INFO_NEW = 'ProductInfoPageNew',
  PRODUCT_CATEGORY = 'CategoryPage',
  PRODUCT_SUBCATEGORY = 'SubCategoryPage',
  PRODUCT_CART = 'CartPage',

  ORDER_SUBMIT = 'OrderSubmitPage',
  ORDER_SEARCH = 'OrderSearchPage',
  ORDER_LIST = 'OrderListPage',
  ORDER_INFO = 'OrderInfoPage',
  ORDER_UPDATE_ADDRESS = 'UpdateAddressSheet',
  ORDER_REVIEW_CREATE = 'OrderReviewCreatePage',
  ORDER_REVIEW_INFO = 'OrderReviewInfoPage',
}
