export enum RouterMap {
  //  首页
  MAIN_INDEX = 'MainIndex',
  // 商户信息
  MERCHANT_DETAIL_PAGE = 'MerchantDetailPage',
  //  菜品详情
  GOODS_DETAIL_PAGE = 'GoodsDetailPage',
  // 确认订单
  CONFIRM_ORDER_PAGE = 'ConfirmOrderPage',
  // 常见问题
  FREQUENT_QUESTION_PAGE = 'FrequentQuestionPage',
  // 订单详情
  ORDER_DETAIL_PAGE = 'OrderDetailPage',
  // 商户位置地图
  HW_MAP_PAGE = 'HwMapPage',
  // 问题详情
  ANSWER_PAGE = 'AnswerPage',
  // 选择优惠券
  SELECT_COUPON_PAGE = 'SelectCouponPage',
  // 我的优惠券
  MY_COUPONS_PAGE = 'MyCouponsPage',
  // 订单备注页面
  REMARKS_PAGE = 'RemarksPage',
  // 图片预览
  PREVIEW_IMAGE_PAGE = 'PreviewImagePage',
  // 选择商户
  SELECT_STORE_PAGE = 'SelectStorePage',
  // 超值加购
  SNACK_SIZED_DEAL_PAGE = 'SnackSizedDealPage',
  // 我的钱包
  MY_WALLET_PAGE = 'MyWalletPage',
  // 超值加购
  RECHARGE_RECORD_PAGE = 'RechargeRecordPage',
  // 储值协议
  WALLET_TERMS_PAGE = 'WalletTermsPage',
  // 确认弹窗
  CONFIRM_DIALOG = 'CommonConfirmDialog',
  // 选择城市
  CITY_SELECT_PAGE = 'CitySelectPage',
  // 预约订座
  PREORDER_PAGE = 'PreorderPage',
  // 排队取号
  QUEUE_PAGE = 'QueuePage',
  // 订座页面
  BOOK_PAGE = 'BookPage',
  // 订座结果页面
  BOOK_RES_PAGE = 'BookResPage',
  // 排号结果页面
  QUEUE_RES_PAGE = 'QueueResPage',
  // 订座订单页面
  BOOK_ORDER_PAGE = 'BookOrderPage',
  // 排号订单页面
  QUEUE_ORDER_PAGE = 'QueueOrderPage',
  // 订单管理页面
  ORDER_LIST_PAGE = 'OrderPage',
  // 我的积分页面
  MY_POINTS_PAGE = 'MyPointsPage',
}
