/*
 * Copyright (c) 2024 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export enum RouterMap {
  // 启动页
  LAUNCH_PAGE = 'LaunchPage',
  // 开屏广告
  LAUNCH_AD_PAGE = 'LaunchAdPage',
  // app隐私
  PRIVACY_POLICY_PAGE = 'PrivacyPolicyPage',
  // app隐私声明
  PRIVACY_STATEMENT_PAGE = 'PrivacyStatement',
  // app隐私声明弹框
  PRIVACY_STATEMENT_ALERT_PAGE = 'PrivacyStatementAlert',
  // 主页
  MAIN_ENTRY = 'MainEntry',
  // 登录
  LOGIN_PAGE = 'LoginPage',

  // -----------------------------------------------------首页
  // 课程列表页面
  COURSE_LIST_PAGE = 'CourseListPage',
  // 直播课程列表页面
  LIVE_STREAMING_LIST_PAGE = 'LiveStreamingListPage',
  // 录播课程详情
  RECORDED_DETAIL_PAGE = 'RecordedDetail',
  // 章节课程详情
  CHAPTER_DETAIL_PAGE = 'ChapterDetail',
  // 搜索页
  SEARCH_PAGE = 'HomeSearch',
  // 习题、下载页
  MATERIAL_PAGE = 'MaterialPage',
  // 答题页面-练习模式
  ANSWER_QUESTIONS_PAGE = 'AnswerQuestionsPage',
  // 答题页面-考试模式
  ANSWER_QUESTIONS_EXAM_PAGE = 'AnswerQuestionsExamPage',
  // 报告页
  ANSWER_REPORT_PAGE = 'TestReportPage',
  // 答题结果评分页
  EXAM_RESULT_PAGE = 'ExamResultPage',
  // 文件预览
  LOOK_FILE_PAGE = 'LookFilePage',
  // -----------------------------------------------------我的
  // 个人信息页
  PERSONAL_INFO_PAGE = 'PersonalInfoPage',
  // 我的收藏
  MY_COLLECTION_PAGE = 'MyCollectionPage',
  // 我的下载
  MY_DOWNLOAD_PAGE = 'MyDownloadPage',
  // 我的错题
  MY_WRONG_QUESTION_PAGE = 'MyWrongQuestionPage',
  // 订单页
  MY_ORDER_PAGE = 'MyOrderPage',
  // 消息通知
  MESSAGE_PAGE = 'MessagePage',
  // 系统消息
  SYSTEM_MESSAGE_PAGE = 'SystemMessage',
  // 课程消息
  COURSE_MESSAGE_PAGE = 'CourseUpdateMessagePage',
  // 意见与反馈
  FEEDBACK_PAGE = 'FeedbackPage',
  // 反馈记录
  FEEDBACK_RECORDS_PAGE = 'FeedbackRecordsPage',
  // 设置
  SETUP_PAGE = 'SetUpPage',
  // 隐私设置
  PRIVACY_SET_PAGE = 'PrivacySetPage',
  // 个人信息收集
  PERSONAL_INFORMATION_PAGE = 'PersonalInformationCollectionPage',
  // 第三方共享信息清单
  DATA_SHARING_PAGE = 'DataSharingPage',
  // 华为账号用户认证协议
  AUTHENTICATION_PAGE = 'AuthenticationPage',
  // 用户服务协议
  USER_AGREEMENT = 'UserAgreement',
  // 登录隐私协议
  PRIVACY_AGREEMENT_PAGE = 'PrivacyAgreementPage',
  // 关于
  ABOUT_PAGE = 'AboutPage',
  // 我的课程
  MY_COURSE_PAGE = 'MyCoursePage',
  // 记录
  MY_COURSE_HISTORY_PAGE = 'WatchHistoryPage',
  // 评论
  MY_COURSE_COMMENTS_PAGE = 'MyCourseCommentsPage',
  // 订单详情页
  ORDER_DETAIL_PAGE = 'OrderDetailPage',
}

