/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2024-2025. All rights reserved.
 */
import { Logger } from '@ohos_agcit/postpartum_care_center_utils';
import { BusinessError } from '@kit.BasicServicesKit';

/**
 * Obtain the error message.
 * @param error BusinessError.
 */
function getErrorHint(error: BusinessError): string {
  const mainErrorMessage: string = error.message.split('.').shift() as string;
  return `${error.code}: ${mainErrorMessage}.`;
}

/**
 * Display the toast message based on the prompt character string or BusinessError.
 * @param error Prompt character string or BusinessError.
 */
export function showToast(context: UIContext, error: BusinessError | string) {
  const message: string = typeof error === 'string' ? error : getErrorHint(error);
  try {
    context.getPromptAction().showToast({
      message,
      duration: 2000
    });
  } catch (error) {
  }
}
