/**
 * 页面路由注册
 */
export class RouterMap {
  // app隐私
  public static readonly PRIVACY_AGREEMENT_PAGE = 'PrivacyAgreementPage'
  // 协议内容页
  public static readonly PROTOCOL_WEB_VIEW_NAME = 'ProtocolWebView'
  // 首页
  public static readonly MAIN_PAGE = 'MainPage'
  // 职位详情页
  public static readonly POSITION_DETAIL_PAGE = 'PositionDetailPage'
  // 公司详情页
  public static readonly COMPANY_DETAIL_PAGE = 'CompanyDetailPage'
  // 筛选页面
  public static readonly FILTER_PAGE = 'FilterPage'
  // 登录页面
  public static readonly LOGIN_PAGE = 'LoginPage'
  // 聊天页面
  public static readonly MESSAGE_CHAT_PAGE = 'MessageChatPage'
  // 创建群组页面
  public static readonly CREATE_GROUP_PAGE = 'CreateGroupPage'
  // 手机联系人添加页面
  public static readonly PHONE_CONTACT_PAGE = 'PhoneContactPage'
  // 从老群组中创建群组页面
  public static readonly CREATE_GROUP_FROM_OLD_GROUP_PAGE = 'CreateGroupFromOldGroupPage'
  // 收藏列表
  public static readonly CHAT_HISTORY_COLLECTION_PAGE = 'ChatHistoryCollectionPage'
  // 查看地理位置页面
  public static readonly VIEW_LOCATION_PAGE = 'ViewLocationPage'
  //转发消息页面
  public static readonly FORWARD_CHAT_PAGE = 'ForwardChatPage'
  //个人详情页
  public static readonly AVATAR_URL_VIEW = 'AvatarUrlView'
  //全屏图片页面
  public static readonly FULL_IMAGE_PAGE = 'FullImagePage'
  //视频播放页面
  public static readonly VIDEO_PAGE_VIEW = 'VideoPageView'
  //消息设置页面
  public static readonly CHAT_SETTINGS = 'ChatSettings'
  // 私聊聊天设置页面
  public static readonly PRIVATE_CHAT_SETTINGS_PAGE = 'PrivateChatSettingsPage'
  //群简介页面
  public static readonly GROUP_INTRODUCTION_VIEW = 'GroupIntroductionView'
  //群管理页面
  public static readonly MEMDER_ROLE_VIEW = 'MemberRoleView'
  //移除群成员页面
  public static readonly DELETE_GROUP_MEMBER_VIEW = 'DeleteGroupMemberView'
  //群管理添加页面
  public static readonly ADD_GROUP_MEMBER_ROLE_VIEW = 'AddGroupMemberRoleView'
  //群管理删除页面
  public static readonly DELETE_GROUP_MEMBER_ROLE_VIEW = 'DeleteGroupMemberRoleView'
  //群公告页面
  public static readonly BULLETIN_VIEW = 'BulletinView'
  // 添加好友页面
  public static readonly ADD_FRIEND_PAGE = 'AddFriendPage'
  //添加群成员页面
  public static readonly ADD_GROUP_MEMBER_VIEW = 'AddGroupMemberView'
  // 聊天历史搜索
  public static readonly CHAT_HISTORY_SEARCH_PAGE = 'ChatHistorySearchPage'
  // 求职经历页面
  public static readonly JOP_APPLICATION_PAGE = 'JobApplicationPage'
  // 投递进度页面
  public static readonly DELIVERY_PROGRESS_PAGE = 'DeliveryProgressPage'
  // 待面试页面
  public static readonly PENDING_INTERVIEW_PAGE = 'PendingInterviewPage'
  // 附件简历页面
  public static readonly RESUME_ATTACHMENT_PAGE = 'ResumeAttachmentPage'
  // 求职意向页面
  public static readonly JOB_INTENTION_PAGE = 'JobIntentionsPage'
  //测试页面
  public static readonly DEMO_PAGE = 'DemoPage'
  // 消息通知页面名称
  public static readonly MESSAGE_CENTER_PAGE = 'MessageCenterPage'
  // 系统消息
  public static readonly SYS_MESSAGE_PAGE = 'SystemMessagePage'
  // 意见反馈
  public static readonly FEEDBACK_PAGE = 'FeedbackPage'
  // 意见反馈历史
  public static readonly FEEDBACK_HISTORY_PAGE = 'FeedbackHistoryPage'
  // 个人信息页
  public static readonly PERSONAL_CENTER_PAGE = 'EditPersonalCenter'
  // 隐私设置
  public static readonly PRIVACY_SETTINGS_PAGE = 'PrivacySettingsPage'
  // 关于
  public static readonly ABOUT_PAGE = 'AboutPage'
  // 使用协议弹框
  public static readonly PRIVACY_USE_PAGE = 'PrivacyUseAlertPage'
  // 三方信息共享清单
  public static readonly PRIVACY_3RD_PARTY_SHARE_PAGE = 'Privacy3rdPartySharePage'
  // 个人信息收集清单
  public static readonly PRIVACY_INFO_COLLECT_PAGE = 'PrivacyInfoCollectPage'
  // 设置页面
  public static readonly SET_UP_PAGE = 'SetUpPage'
  // 搜索框
  public static readonly SEARCH_PAGE = 'SearchPage'
  // 城市选择
  public static readonly CITY_SELECT_PAGE = 'CitySelectPage'
  // 简历-在线简历
  public static readonly RESUME_PAGE = 'ResumePage'
  // 简历-在线简历预览页
  public static readonly RESUME_PREVIEW_PAGE = 'ResumePreviewPageBuilder'
  // 简历-个人信息编辑页
  public static readonly RESUME_PERSONAL_INFO_PAGE = 'ResumePersonalInformationPage'
  // 简历-自我评价编辑
  public static readonly RESUME_SELF_EVALUATION_PAGE = 'SelfEvaluationPage'
  // 简历-求职意向编辑
  public static readonly RESUME_CAREER_OBJECTIVE_PAGE = 'CareerObjectivePage'
  // 简历-工作经历编辑页
  public static readonly RESUME_WORK_EXPERIENCE_PAGE = 'ResumeWorkExperiencePage'
  // 简历-项目经验编辑页
  public static readonly RESUME_PROJECT_EXPERIENCE_PAGE = 'ResumeProjectExperiencePage'
  // 简历-教育背景编辑页
  public static readonly RESUME_EDUCATION_BACKGROUND_PAGE = 'ResumeEducationBackgroundPage'
  // 简历-职业技能编辑
  public static readonly RESUME_VOCATIONAL_SKILL_PAGE = 'VocationalSkillPage'
  // 简历-资格证书选择
  public static readonly RESUME_QUALIFICATION_CERTIFICATE_PAGE = 'QualificationCertificatePage'
  // 简历-职位选择
  public static readonly RESUME_POSITION_SELECT_PAGE = 'PositionSelectPage'
  // 简历-行业选择
  public static readonly RESUME_INDUSTRY_SELECT_PAGE = 'IndustrySelectPage'
  // 简历-工作描述编辑
  public static readonly RESUME_WORK_DESCRIPTION_PAGE = 'WorkDescriptionPage'
  // 简历-项目经验-角色选择
  public static readonly RESUME_ROLE_SELECT_PAGE = 'RoleSelectPage'
  // 简历-项目经验-项目描述编辑
  public static readonly RESUME_PROJECT_DESCRIPTION_PAGE = 'ProjectDescriptionPage'
}

