export class IColor {
  // 纯白色
  public static readonly WHITE: ResourceStr = '#FFFFFFFF';
  // 淡灰色 85% 透明
  public static readonly GRAY_LIGHT_TRANSPARENT_85: ResourceStr = '#D9FAFAFA';
  // 超淡灰色 95% 透明 (用于背景色)
  public static readonly BACKGROUND: ResourceStr = '#F2F1F3F5';
  // 高亮红粉色 (用于主题色)
  public static readonly THEME_PRIMARY: ResourceStr = '#FFE64566';
  // 黑色 5% 透明
  public static readonly BLACK_TRANSPARENT_5: ResourceStr = '#0D000000';
  // 黑色 20% 透明
  public static readonly BLACK_TRANSPARENT_20: ResourceStr = '#33000000';
  // 黑色 40% 透明
  public static readonly BLACK_TRANSPARENT_40: ResourceStr = '#66000000';
  // 黑色 60% 透明
  public static readonly BLACK_TRANSPARENT_60: ResourceStr = '#99000000';
  // 黑色 90% 透明
  public static readonly BLACK_TRANSPARENT_90: ResourceStr = '#E6000000';
  // 链接跳转颜色
  public static readonly LINK: ResourceStr = '#FF0A59F7';
}
