export enum AppStorageKeys {CURRENT_BREAK_POINT = "CURRENT_BREAK_POINT",
  CURRENT_DISPLAY_ORIENTATION = "CURRENT_DISPLAY_ORIENTATION",
  STATUS_BAR_HEIGHT = "STATUS_BAR_HEIGHT",
  AI_GUIDE_BAR_HEIGHT = "AI_GUIDE_BAR_HEIGHT",
  CUR_TAB_INDEX = "CUR_TAB_INDEX",
  SMS_CODE_REQ_TIME = "SMS_CODE_REQ_TIME",
  EMAIL_CODE_REQ_TIME = "EMAIL_CODE_REQ_TIME",
  NETWORK_CONNECTED = "NETWORK_CONNECTED",
  CURRENT_COLOR_MODE = "CURRENT_COLOR_MODE",
  DEFAULT_MODEL_PAGE_SHOW = "DEFAULT_MODEL_PAGE_SHOW",
  EXTRA_MODEL_PAGE_SHOW = "EXTRA_MODEL_PAGE_SHOW",
  USER_INFO_STATUS = "USER_INFO_STATUS",
  MESSAGE_UNREAD_NUMBER = "MESSAGE_UNREAD_NUMBER"
}