/**
 * 所有组件的颜色常量
 */
export default class ColorConstants {
  /**
   * 花瓣外层颜色
   */
  static readonly FLOWER_OUT_COLOR: string = '#ED6E21'
  /**
   * 花瓣内层颜色
   */
  static readonly FLOWER_INNER_COLOR: string = '#F8A01E'
  /**
   * 外圆颜色
   */
  static readonly OUT_CIRCLE_COLOR: string = '#F7CD03'
  /**
   * 白色
   */
  static readonly WHITE_COLOR: string = '#FFFFFF'
  /**
   * 内圆颜色
   */
  static readonly INNER_CIRCLE_COLOR: string = '#F8A01E'
  /**
   * 粉色扇形颜色
   */
  static readonly ARC_PINK_COLOR: string = '#FFC6BD'
  /**
   * 黄色扇形颜色
   */
  static readonly ARC_YELLOW_COLOR: string = '#FFEC90'
  /**
   * 绿色扇形颜色
   */
  static readonly ARC_GREEN_COLOR: string = '#ECF9C7'
  /**
   * 文本颜色
   */
  static readonly TEXT_COLOR: string = '#ED6E21'
}