export enum AppStorageMap {
  HUAWEI_ACCOUNT = 'huaweiAccount',
  USER_INFO = 'userInfo',
}

export enum RouterMap {
  // 我的-修改个人信息
  MINE_PROFILE_EDIT = 'ProfileEditPage',
  // 门票订单
  TICKET_ORDERS = 'TicketOrders',
  // 省博介绍
  INTRODUCE = 'IntroducePage',
  // 特展详情
  PERFORMANCE_DETAIL = 'PerformanceDetail',
  // 门票详情
  TICKET_DETAIL = 'TicketDetail',
  // 门票预定
  ORDER_TICKET = 'OrderTicket',
  // 门票信息填写
  ORDER_EDIT = 'OrderEditPage',
  //  讲解服务
  EXPLAIN = 'ExplainPage',
  // 场馆地图
  MAP = 'MapPage',
  // 停车缴费
  PARKING = 'ParkingPage',
  // 隐私政策
  PRIVACY = 'PrivacyPage',
  // 预约信息
  ORDER_INFO = 'OrderInfo',
  //  预约成功
  ORDER_SUCCESS = 'OrderSuccess',
  //   购票成功
  BUY_SUCCESS = 'BuySuccess',
  //   购票信息
  BUY_INFO = 'BuyInfo',
  //   特展预约
  PERFORMANCE_PAGE = 'PerformancePage',
  //   付费购票
  BUY_TICKET = 'BuyTicket',
  //  讲解预约
  EXPLAIN_ORDER_PAGE = 'ExplainOrderPage',
  //  馆藏珍品
  TREASURE_PAGE = 'TreasurePage',
  //  活动页面
  ACTIVE_PAGE='ActivePage',
  //  活动详情
  ACTIVE_DETAIL='ActiveDetail',
  //  参加活动
  Join_Active_Page='JoinActivePage',
  //  活动确认
  ACTIVE_SUCCESS='ActiveSuccess',
  //  讲解订单
  EXPLAIN_ORDERS = 'ExplainOrders',
  //  活动订单
  ACTIVE_ORDERS = 'ActiveOrders',
  //  讲解预约成功
  EXPLAIN_SUCCESS = 'ExplainSuccess',
  //  讲解订单详情
  EXPLAIN_ORDER_DETAIL = 'ExplainOrderDetail',
  //  活动订单详情
  ACTIVE_ORDER_DETAIL = 'ActiveOrderDetail'
}

